### ISSUE TITLE
Podcasts functions seems not to work entirely?!

### ISSUE THREAD

**Issue by nicmare** [jwilsson/spotify-web-api-php#186]
I could start a request by using
`$track = $api->getTrack('6bPnY2qoxpP6pYVGFIeoXG');`
or
`$artist = $api->getArtist('0flK7a9sS4TEcCYVNUaiXU');`

that works!

now i want to retrieve some infos about podcasts. for example this one: `spotify:show:7nwKLoptCS7YFNKpDkti3p`
but when i try this: 
`$episodes = $api->getShowEpisodes('7nwKLoptCS7YFNKpDkti3p');`
i get a critical error:
```
[22-Apr-2020 15:43:54 UTC] PHP Fatal error:  Uncaught SpotifyWebAPI\SpotifyWebAPIException: non existing id in /Users/nicb/Data/_htdocs/kadh/wp-content/themes/bootstrap/vendor/jwilsson/spotify-web-api-php/src/Request.php:56
Stack trace:
#0 /Users/nicb/Data/_htdocs/kadh/wp-content/themes/bootstrap/vendor/jwilsson/spotify-web-api-php/src/Request.php(265): SpotifyWebAPI\Request->parseBody(Object(stdClass), 404)
#1 /Users/nicb/Data/_htdocs/kadh/wp-content/themes/bootstrap/vendor/jwilsson/spotify-web-api-php/src/Request.php(137): SpotifyWebAPI\Request->send('GET', 'https://api.spo...', '', Array)
#2 /Users/nicb/Data/_htdocs/kadh/wp-content/themes/bootstrap/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(86): SpotifyWebAPI\Request->api('GET', '/v1/shows/7nwKL...', Array, Array)
#3 /Users/nicb/Data/_htdocs/kadh/wp-content/themes/bootstrap/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(1286): SpotifyWebAPI\SpotifyWebAPI->sendRequest('GET', '/v1/shows/7nwKL...', Array)
#4 /Users/nicb/Data/_htdocs/kadh/wp-content/themes/bootstrap/functions.ph in /Users/nicb/Data/_htdocs/kadh/wp-content/themes/bootstrap/vendor/jwilsson/spotify-web-api-php/src/Request.php on line 56

```
what is wrong here?

**Comment by nicmare** [comment]
okay. after looking into spotify docs directly, i found out "market" option is required. Seem to work now like this:

`$show = $api->getShow('7butYcpxarLP55AfoCHjU7',array("market"=>"DE"));
`
