### ISSUE TITLE
Suddenly getting PHP errors

### ISSUE THREAD

**Issue by emilstahl** [jwilsson/spotify-web-api-php#53]
Hi

I haven't changed anything. Suddenly I'm getting `500 Internal Server Error` and these PHP errors:

```
2016/09/19 19:56:13 [error] 15765#15765: *218387 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined index: id in /var/www/spotify.srv1.dk/index.php on line 5" while reading response header from upstream, client: 86.52.22.143, server: spotify.srv1.dk, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "spotify.srv1.dk"
2016/09/19 19:56:16 [error] 15765#15765: *218387 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught SpotifyWebAPI\SpotifyWebAPIException: An unknown error occurred. in /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php:38
Stack trace:
#0 /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php(188): SpotifyWebAPI\Request->parseBody(Object(stdClass), 404)
#1 /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php(101): SpotifyWebAPI\Request->send('GET', 'https://api.spo...', '', Array)
#2 /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(851): SpotifyWebAPI\Request->api('GET', '/v1/tracks/5NDa…', Array, Array)
#3 /var/www/spotify.srv1.dk/index.php(13): SpotifyWebAPI\SpotifyWebAPI->getTrack('5NDaKOiioQHfDOb…')
#4 {main}
  thrown in /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php on line 38" while reading response header from upstream, client: 86.52.22.143, server: spotify.srv1.dk, request: "GET /?id=5NDaKOiioQHfDObHIl4dOP HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "spotify.srv1.dk", referrer: "http://spotify.srv1.dk/"
2016/09/19 19:56:17 [error] 15765#15765: *218387 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught SpotifyWebAPI\SpotifyWebAPIException: An unknown error occurred. in /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php:38
Stack trace:
#0 /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php(188): SpotifyWebAPI\Request->parseBody(Object(stdClass), 404)
#1 /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php(101): SpotifyWebAPI\Request->send('GET', 'https://api.spo...', '', Array)
#2 /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(851): SpotifyWebAPI\Request->api('GET', '/v1/tracks/5NDa…', Array, Array)
#3 /var/www/spotify.srv1.dk/index.php(13): SpotifyWebAPI\SpotifyWebAPI->getTrack('5NDaKOiioQHfDOb…')
#4 {main}
  thrown in /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php on line 38" while reading response header from upstream, client: 86.52.22.143, server: spotify.srv1.dk, request: "GET /?id=5NDaKOiioQHfDObHIl4dOP HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "spotify.srv1.dk"
2016/09/19 19:56:17 [error] 15765#15765: *218387 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught SpotifyWebAPI\SpotifyWebAPIException: An unknown error occurred. in /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php:38
Stack trace:
#0 /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php(188): SpotifyWebAPI\Request->parseBody(Object(stdClass), 404)
#1 /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php(101): SpotifyWebAPI\Request->send('GET', 'https://api.spo...', '', Array)
#2 /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(851): SpotifyWebAPI\Request->api('GET', '/v1/tracks/5NDa…', Array, Array)
#3 /var/www/spotify.srv1.dk/index.php(13): SpotifyWebAPI\SpotifyWebAPI->getTrack('5NDaKOiioQHfDOb…')
#4 {main}
  thrown in /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php on line 38" while reading response header from upstream, client: 86.52.22.143, server: spotify.srv1.dk, request: "GET /?id=5NDaKOiioQHfDObHIl4dOP HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "spotify.srv1.dk"
2016/09/19 19:56:18 [error] 15765#15765: *218387 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught SpotifyWebAPI\SpotifyWebAPIException: An unknown error occurred. in /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php:38
Stack trace:
#0 /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php(188): SpotifyWebAPI\Request->parseBody(Object(stdClass), 404)
#1 /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php(101): SpotifyWebAPI\Request->send('GET', 'https://api.spo...', '', Array)
#2 /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/SpotifyWebAPI.php(851): SpotifyWebAPI\Request->api('GET', '/v1/tracks/5NDa…', Array, Array)
#3 /var/www/spotify.srv1.dk/index.php(13): SpotifyWebAPI\SpotifyWebAPI->getTrack('5NDaKOiioQHfDOb…')
#4 {main}
  thrown in /var/www/spotify.srv1.dk/vendor/jwilsson/spotify-web-api-php/src/Request.php on line 38" while reading response header from upstream, client: 86.52.22.143, server: spotify.srv1.dk, request: "GET /?id=5NDaKOiioQHfDObHIl4dOP HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "spotify.srv1.dk"
```

`PHP Version 7.0.8`

**Comment by jwilsson** [comment]
This should be fixed by 13d3b9417f0dc6de959867281ae0e4c9392f9c8d and just released as `1.3.4`. Sorry about that!

**Comment by emilstahl** [comment]
Thanks @jwilsson – it works! 👍

**Comment by moop6535** [comment]
This is happening to me now. I am on latest version 1.10.0
